### PR TITLE
localization: add translation for zh_TW

### PR DESCRIPTION
**Pull request by Rplus**
copy from `zh_CN`,
and adjust the diction in localization.

### CODE REVIEW

**Comment by cool91788** [comment]
有發現一些錯字，可直接修改？.還是？

**Comment by Rplus** [comment]
@cool91788 可否幫忙指出錯字位置呢？ 感謝。

**Comment by cool91788** [comment]
string.xml 第289行
彈出鍵盤未知 >> 彈出鍵盤位置

至於要不要一些改成台灣的用語就看妳了～

**Comment by Rplus** [comment]
OK~ 感謝指正！

其實我不太清楚 `popup_keyboard` 指的是什麼東西

**Comment by cool91788** [comment]
popup_keyboard 直翻就是 彈出式鍵盤.
就是按一下螢幕會有鍵盤跳出來的那個東西
STORE-LISTING
第10行改成   mosh 官方支援 比較好(?

**Comment by Rplus** [comment]
ok! Thank you, I fixed them~

**Comment by rypervenche** [comment]
I noticed that there are still many PRC versions of words in this pull request. I have forked the repo and am working on making changes off of this pull request and will submit it as soon as I finish.

**Comment by rypervenche** [comment]
It's taking a little bit longer than anticipated, but it's getting done. Hope to have it done sometime this week.

**Comment by coin3x** [comment]
我也來翻譯好了 借用 @Rplus 的 repo~
然後希望能夠趕上樓上那位仁兄 xD

**Comment by coin3x** [comment]
@Rplus 我要發 PR 到你的 repo 嗎 ouo?

**Comment by rypervenche** [comment]
About 70% complete now, the progress can be seen on my github here: https://github.com/rypervenche/juicessh-translations/tree/zh_TW

Sorry for taking so long to get it done. Life things going on. Thanks!

**Comment by Rplus** [comment]
good job ~

**Comment by coin3x** [comment]
@rypervenche I fixed A LOT translation and translated all file. Please merge the PR :)

**Comment by rypervenche** [comment]
We have fixed all of the issues in this PR in a fork of this branch. See #31 . Thanks!

**Comment by TomMaddox** [comment]
Have merged #31 and think this PR is now no longer needed

**Pull request closed without merging**
