### PR TITLE
localization: add translation for zh_TW (corrected)

### PR DESCRIPTION
**Pull request by rypervenche**
This is a fork of pull request #16 . We have fixed a ton of words that were zh_CN words that had simply been converted into the traditional script and not properly localized to zh_TW.

### CODE REVIEW

**Comment by coin3x** [comment]
@rypervenche Please merge my latest PR.

**Comment by rypervenche** [comment]
The typos have been fixed and the pull request is ready to be merged.

**Comment by Rplus** [comment]
+1

**Comment by TomMaddox** [comment]
Thanks for your efforts both.
@Rplus - You should receive an email shortly with pro version upgrade details.
@rypervenche - Please email us at support@sonelli.com if you would like to claim a free upgrade.

Thanks again, Tom

**Comment by Rplus** [comment]
@TomMaddox Thank you! :+1:

**Comment by coin3x** [comment]
uh...

**Pull request merged**
